version: '3.8'
services:
  client:
    build: .
    container_name: cinema-rest-frontend
    ports:
      - '3000:3000'
    volumes:
      - /src
      - /app/node_modules
    stdin_open: true
    tty: true